# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish on npm 

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - main
    tags:
      - v1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - run: ls
      - run: npm run post
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist_pre
          path: |
            dist
      - run: cd dist && ls
        name: publish Pages 2r
      - run: cd .. && ls
      - run: npm run build:docs
      - name: Upload docs folder
        uses: actions/upload-artifact@v4
        with:
          name: docs_pre
          path: |
            docs

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
          cache: 'npm'
      - name: Download Docs
        uses: actions/download-artifact@v5
        with:
          name: docs_pre
          path: |
            docs    
      - name: Download dist
        uses: actions/download-artifact@v5
        with:
          name: dist_pre
          path: |
            dist
      - run: ls
      - run: |
          cd dist && ls
          npm publish --provenance --access public --loglevel verbose
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
